### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by billimek** [netsparker/Netsparker-Cloud-GitHub-Actions#1]
Hello,

I notice that this repo doesn't have a license file and would very much like to use it and/or contribute.  Would you be willing to add a license to this repo?  The [package.json shows an 'ISC' license](https://github.com/netsparker/Netsparker-Cloud-GitHub-Actions/blob/master/package.json#L13) and if it makes things easier, I can open a pull request to add that license file to the repo root.

**Comment by kiliczsh** [comment]
MIT license is added with [this commit](https://github.com/netsparker/Netsparker-Cloud-GitHub-Actions/commit/3e21c7c1d24938a36675fcd04134d0418b49f4ff). Thanks @billimek 🚀
