### ISSUE TITLE
Base URL is no longer optional

### ISSUE THREAD

**Issue by willryan-stemcell** [netsparker/Netsparker-Cloud-GitHub-Actions#18]
The readme.md should be updated:

```
  if (isEmpty(baseUrl)) {
    core.setFailed(`Base URL is missing. Please check your generated script.`);
    return;
```

> base-url:
> Optional Website URL for Netsparker Enterprise.

**Comment by kiliczsh** [comment]
@willryan-stemcell thanks for warning, just updated readme and action.yaml 🚀
