### ISSUE TITLE
Semver, release v1.0.0

### ISSUE THREAD

**Issue by cschroedl-gov** [netsparker/Netsparker-Cloud-GitHub-Actions#19]
User story:
As a user whose project uses both this integration and a software composition analysis (SCA) solution (e.g. [GitHub Dependabot](https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions), [Mend's Renovate](https://docs.renovatebot.com/) etc.) I want to configure my SCA tool to automatically merge minor and patch versions of my project's dependencies when CI tests pass, and to require manual review for major versions in my dependency versions. This enables my project to efficiently stay up to date with most changes while preserving stability.

To support this goal, could this integration please adopt [semantic versioning](https://semver.org/) and explicitly indicate that in its README?

https://semver.org/#how-do-i-know-when-to-release-100 says...

> How do I know when to release 1.0.0?
>If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backward compatibility, you should probably already be 1.0.0.

Could version 1.0.0 please be released to reflect that this integration is being used in production and to ensure developers and SCA tools have clear expectations about breaking and non-breaking changes?

**Comment by kiliczsh** [comment]
@cschroedl-gov [this commit](https://github.com/netsparker/Netsparker-Cloud-GitHub-Actions/commit/b6b1b5b1067caa0b3b99aec22cd3e07f0ee28196) should solve this issue if not let me know please

**Comment by cschroedl-gov** [comment]
Looks great! Thank you for the speedy delivery 🚀
