### ISSUE TITLE
Warning from GitHub Actions - Deprecated command: set-output

### ISSUE THREAD

**Issue by willryan-stemcell** [netsparker/Netsparker-Cloud-GitHub-Actions#3]
In my GitHub Actions logs, I see the following error relating to `netsparker/Netsparker-Cloud-GitHub-Actions@v0.0.1`:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Please update the code for setting the output to use the GitHub recommended formatting:
```
- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```

**Comment by esteban-go** [comment]
Please review this change, "set-output" still being used on the release v0.1.0

**Comment by kiliczsh** [comment]
@willryan-stemcell https://github.com/netsparker/Netsparker-Cloud-GitHub-Actions/commit/cba073d88b272b87609eb9e2a955d23ba0c8e027
