### ISSUE TITLE
Still receive deprecated errors in logs

### ISSUE THREAD

**Issue by willryan-stemcell** [netsparker/Netsparker-Cloud-GitHub-Actions#9]
@kiliczsh Please see my comments in https://github.com/netsparker/Netsparker-Cloud-GitHub-Actions/issues/3#issuecomment-1935419280

**Comment by kiliczsh** [comment]
@willryan-stemcell with the [v0.1.2](https://github.com/netsparker/Netsparker-Cloud-GitHub-Actions/releases/tag/v0.1.2) the issue should have been fixed. Bumping @actions/core dependency to ^1.10.0  is only solution available.
